Instrument ID, arm, camera, mediapipe set up

In [1]:
import os 
import sys
import cv2
import numpy as np
import math
import pyrealsense2 as rs
import time
import struct
import socket
import torch
import random
# Import modules from voice-control-instrument-id/voice_instrument_functions.py
#instrument_module_path = os.path.abspath(os.path.join(__file__, "..", "..", "voice-control-instrument-id"))
notebook_path = os.getcwd()  # Current working directory
instrument_module_path = os.path.abspath(os.path.join(notebook_path, "..", "voice-control-instrument-id"))
sys.path.append(instrument_module_path) 
from voice_instrument_functions import *
from audio_utils import *

# Load instrument identification model
inst_model = load_model('../voice-control-instrument-id/models/instrument_detector_model.pt', False)

from robot_control_functions import * # Because of mediapipe, need to import AFTER loading instrument id model

# Set up MyCoBot 280
HOST = "10.42.0.1"
GET_COORDS_PORT = 5006
MOVE_COORDS_PORT = 5005
MOVE_GRIPPER_PORT = 5007
home = [90, 0, 0, -90, 0, -45]

# Set up Mediapipe hand tracking
mp_hands = mp.solutions.hands
mp_drawing = mp.solutions.drawing_utils
hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=1,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5)

# Set up depth camera
# TODO: open as a window for Design Day
pipeline = rs.pipeline()
config = rs.config()
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)
profile = pipeline.start(config)

#inst_img = get_camera_img(pipeline)

c:\Users\maxis\anaconda3\envs\dt12\lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
Using cache found in C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2025-4-17 Python-3.9.21 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)

Fusing layers... 
Model summary: 267 layers, 46167513 parameters, 0 gradients, 107.8 GFLOPs
Adding AutoShape... 


Voice activation set up - ONLY RUN THIS IF YOU WANT TO SET A CUSTOM VOICE

In [2]:
choose_tts_voice()


Available English TTS Voices:
[0] Microsoft David Desktop - English (United States) (HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_DAVID_11.0)
[1] Microsoft Zira Desktop - English (United States) (HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0)
Selected voice: Microsoft David Desktop - English (United States)



Main Script

In [3]:
while True:
    home = [90, 0, 0, -90, 0, -45]
    home[3] = home[3] + random.randint(0, 5)
    
    send_coords(home, HOST, MOVE_COORDS_PORT, 1) # send robot to home
    time.sleep(2) # TODO: better way to wait for arm to be stable before getting frame of tray
    inst_img = get_camera_img(pipeline) # get png of tray to run instrument id

    #command = get_voice_command(porcupine, cobra, recorder) # get voice command
    #inst = get_instrument_name(command) # transcribe voice command and get name of instrument
    #instruments = get_instrument_name()
    #inst = instruments[0][0] ### HARD CODED TO JUST TAKE THE FIRST INSTRUMENT IN THE LIST
    inst = 'scissors'
    x_mid, y_mid = identify_instrument(inst_model, inst_img, inst) # get 2d coords of instrument

    ## Get color and depth frame
    frames = pipeline.poll_for_frames()
    if not frames:
        continue

    depth_frame = frames.get_depth_frame()
    color_frame = frames.get_color_frame()

    # Convert yolo instrument coords to 3D coords
    inst_coords = get_inst_coords(color_frame, depth_frame, x_mid, y_mid)
    print(inst_coords)

    # target_coords = inst_coords + [home[3], home[4], home[5]]
    coords = get_coords(HOST, GET_COORDS_PORT)
    if coords is None:
            print("Robot did not return coordinates")
            continue
    
    curr_coords = list(coords)
    target_coords = transform_camera_to_robot(inst_coords, curr_coords[:3], curr_coords[3:])
    target_coords = list(target_coords) + curr_coords[3:]
    print(target_coords)

    pickSequence(target_coords, HOST, MOVE_COORDS_PORT, MOVE_GRIPPER_PORT)
    time.sleep(5)

Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[83.06780435855866, 128.8000030517578, 502.20001220703125, -115.66999816894531, -42.20000076293945, 17.989999771118164]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[83.06780435855866, 134.0999984741211, 396.20001220703125, 178.00999450683594, 2.359999895095825, 44.95000076293945]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (378, 135) | Confidence: 0.83 | Class: Surgical Scissors Sharp/Sharp
[     71.584     -24.111       272.6]
[120.95603890226992, 220.1667708522473, 135.07329468257666, -177.8300018310547, -1.9299999475479126, 44.959999084472656]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.49155985855866, 138.0999984741211, 401.8999938964844, -178.32000732421875, -0.23999999463558197, 46.66999816894531]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[83.1830515, 140.3000030517578, 405.79998779296875, -176.89999389648438, -2.869999885559082, 45.0099983215332]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.83730567927932, 139.0, 403.20001220703125, -178.13999938964844, -1.3700000047683716, 45.15999984741211]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (107, 108) | Confidence: 0.94 | Class: Surgical Scissors Sharp/Sharp
[    -34.756     -145.05       249.6]
[-66.47677573091116, 213.20596876099734, 150.8204766494179, -179.8699951171875, 0.6200000047683716, 45.08000183105469]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (127, 155) | Confidence: 0.69 | Class: Surgical Scissors Sharp/Sharp
[     -48.15      -123.6       263.3]
[-62.96043996777155, 212.0915938305967, 149.06100587443507, -176.44000244140625, -2.9200000762939453, 46.5099983215332]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (121, 125) | Confidence: 0.84 | Class: Surgical Scissors Sharp/Sharp
[    -36.127      -134.6       254.1]
[-64.12529610098115, 212.24042550875888, 151.89628371560977, -178.3300018310547, -0.7200000286102295, 46.93000030517578]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.33907085855866, 141.4000015258789, 406.1000061035156, -176.50999450683594, -2.75, 46.959999084472656]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.33907085855866, 139.0, 401.6000061035156, -178.82000732421875, -0.3100000023841858, 45.880001068115234]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (326, 84) | Confidence: 0.43 | Class: Surgical Scissors Sharp/Sharp
[     68.208     -66.837         260]
[81.61033325329977, 233.7250080217252, 140.21059657293512, -179.92999267578125, 0.05999999865889549, 45.43000030517578]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.72205414144135, 139.5999984741211, 404.0, -177.74000549316406, -1.850000023841858, 46.290000915527344]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.72205414144135, 139.8000030517578, 404.3999938964844, -177.52000427246094, -1.9900000095367432, 45.22999954223633]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.606807, 140.4000015258789, 405.6000061035156, -176.83999633789062, -2.559999942779541, 45.20000076293945]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.72205414144135, 140.0, 404.8999938964844, -177.33999633789062, -2.309999942779541, 45.29999923706055]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.72205414144135, 138.0999984741211, 401.29998779296875, -179.19000244140625, -0.4300000071525574, 44.90999984741211]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.72205414144135, 139.5, 403.8999938964844, -177.82000732421875, -1.7999999523162842, 44.970001220703125]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.72205414144135, 126.80000305175781, 386.1000061035156, 171.94000244140625, 8.260000228881836, 44.119998931884766]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.37630832072067, 138.5, 402.1000061035156, -178.44000244140625, -0.5600000023841858, 45.08000183105469]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.72205414144135, 138.5999984741211, 402.29998779296875, -178.6300048828125, -0.8700000047683716, 45.08000183105469]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (347, 108) | Confidence: 0.93 | Class: Surgical Scissors Sharp/Sharp
[     68.372     -48.611       266.8]
[97.2199713710659, 237.15787922212127, 142.51602955801428, -177.57000732421875, -2.049999952316284, 45.04999923706055]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.91531535855866, 141.0999984741211, 407.29998779296875, -175.27000427246094, -2.7799999713897705, 46.09000015258789]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (316, 139) | Confidence: 0.96 | Class: Surgical Scissors Sharp/Sharp
[     40.281      -48.04       261.8]
[74.11399302314837, 217.30464651735696, 146.93761628588442, -177.3300018310547, -2.059999942779541, 45.04999923706055]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.606807, 137.5, 400.6000061035156, -179.24000549316406, 0.2199999988079071, 46.400001525878906]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (466, 99) | Confidence: 0.85 | Class: Surgical Scissors Sharp/Sharp
[     126.83    -0.67502       270.9]
[182.7005185793932, 229.86137360382918, 129.60898177279887, -179.44000244140625, 0.05000000074505806, 45.2599983215332]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (325, 205) | Confidence: 0.97 | Class: Surgical Scissors Sharp/Sharp
[     15.523     -15.542       260.3]
[82.44724495668562, 170.848932622666, 142.99783684207893, -178.77999877929688, -1.2699999809265137, 46.29999923706055]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (462, 105) | Confidence: 0.33 | Class: Surgical Scissors Sharp/Sharp
[     122.55    -0.22202       271.6]
[175.95495805856734, 233.74658300188327, 130.50680399903723, -179.4600067138672, -0.46000000834465027, 48.41999816894531]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.68481667927932, 139.0, 399.29998779296875, -179.39999389648438, 1.409999966621399, 46.400001525878906]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.72205414144135, 140.5, 401.79998779296875, -178.8800048828125, -0.6200000047683716, 45.2599983215332]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (224, 91) | Confidence: 0.83 | Class: Surgical Scissors Sharp/Sharp
[     21.792     -108.93         263]
[9.815609707149259, 239.66329152002896, 141.87988451444386, -178.75999450683594, -0.8700000047683716, 45.25]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (231, 82) | Confidence: 0.38 | Class: Surgical Scissors Sharp/Sharp
[     27.686     -105.21       252.4]
[10.36530148711008, 235.79893056652685, 151.85602392786743, -178.6300048828125, -0.14000000059604645, 46.66999816894531]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.10857217927932, 138.0999984741211, 400.8999938964844, -178.80999755859375, 0.4000000059604645, 46.7599983215332]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.68481667927932, 137.5, 399.5, -179.99000549316406, 0.7400000095367432, 45.869998931884766]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.91531535855866, 137.5, 399.5, 179.80999755859375, 0.5600000023841858, 45.779998779296875]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (257, 98) | Confidence: 0.87 | Class: Surgical Scissors Sharp/Sharp
[     32.518     -90.735       260.9]
[31.531682853715758, 241.61155439193098, 149.14915603079015, -177.52000427246094, -2.119999885559082, 45.75]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.56956514144134, 139.6999969482422, 402.79998779296875, -178.36000061035156, -1.2400000095367432, 47.880001068115234]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (277, 135) | Confidence: 0.94 | Class: Surgical Scissors Sharp/Sharp
[     25.363     -65.425       259.4]
[45.01831373671963, 210.65272600294838, 145.2037580921429, -178.50999450683594, -0.8700000047683716, 46.040000915527344]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (283, 139) | Confidence: 0.50 | Class: Surgical Scissors Sharp/Sharp
[     25.925     -61.532       260.3]
[46.55614852671844, 210.66171893563438, 145.64683474011366, -178.02999877929688, -1.159999966621399, 46.91999816894531]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (289, 170) | Confidence: 0.27 | Class: Surgical Scissors Sharp/Sharp
[     16.051     -47.991       270.9]
[47.885020778134106, 210.6238764456677, 141.74544725388853, -175.77999877929688, -3.140000104904175, 47.029998779296875]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (290, 139) | Confidence: 0.92 | Class: Surgical Scissors Sharp/Sharp
[     29.095     -59.014       260.6]
[47.72747975699288, 210.18064237272762, 144.84580933479657, -177.8300018310547, -0.6100000143051147, 47.11000061035156]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.22381932072068, 139.1999969482422, 401.8999938964844, -178.50999450683594, -0.4099999964237213, 47.20000076293945]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (359, 119) | Confidence: 0.96 | Class: Surgical Scissors Sharp/Sharp
[     69.473      -39.03       269.9]
[102.0655760570005, 227.66802382073604, 136.41766322123448, -178.0800018310547, -1.309999942779541, 46.040000915527344]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (356, 91) | Confidence: 0.96 | Class: Surgical Scissors Sharp/Sharp
[      77.88     -51.399       260.6]
[96.87899307081567, 228.21896527655724, 138.8281569784312, -179.5399932861328, 0.6700000166893005, 46.58000183105469]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (348, 125) | Confidence: 0.94 | Class: Surgical Scissors Sharp/Sharp
[      61.81     -41.418       269.9]
[90.78251180933852, 225.6548184771803, 137.52358121827302, -177.42999267578125, -1.3200000524520874, 46.83000183105469]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.91531535855866, 135.5, 397.20001220703125, 179.25999450683594, 2.440000057220459, 46.709999084472656]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (329, 127) | Confidence: 0.91 | Class: Surgical Scissors Sharp/Sharp
[     53.491     -49.258       273.9]
[92.24349725297036, 228.23251988388108, 135.22737353933763, -178.1699981689453, -2.7799999713897705, 44.31999969482422]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.37630832072067, 137.4000015258789, 400.5, -179.3000030517578, 0.28999999165534973, 46.400001525878906]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (148, 155) | Confidence: 0.87 | Class: Surgical Scissors Sharp/Sharp
[    -38.669     -113.35       262.1]
[-43.916378849827254, 201.70384246442407, 144.2495053437707, -178.07000732421875, -1.309999942779541, 45.25]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (173, 132) | Confidence: 0.87 | Class: Surgical Scissors Sharp/Sharp
[    -16.974     -108.74       252.7]
[-22.939152823928673, 204.2805877969149, 149.39902702908086, -179.4499969482422, -0.5699999928474426, 46.84000015258789]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (161, 124) | Confidence: 0.96 | Class: Surgical Scissors Sharp/Sharp
[    -18.552      -117.1       252.4]
[-35.09017648626025, 206.6835830102103, 149.8871866729434, -179.25, 0.10000000149011612, 47.02000045776367]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.33907085855866, 142.0999984741211, 407.3999938964844, -175.91000366210938, -3.509999990463257, 46.91999816894531]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.33907085855866, 140.6999969482422, 404.70001220703125, -177.13999938964844, -2.0, 45.93000030517578]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.68481667927932, 140.6999969482422, 404.70001220703125, -177.38999938964844, -2.240000009536743, 45.91999816894531]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (237, 116) | Confidence: 0.93 | Class: Surgical Scissors Sharp/Sharp
[     16.139     -89.435       254.7]
[19.561606075188507, 215.08806139903422, 147.27730410774495, -179.44000244140625, -0.3100000023841858, 45.959999084472656]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.33907085855866, 141.5, 406.20001220703125, -176.4499969482422, -2.809999942779541, 46.95000076293945]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (234, 107) | Confidence: 0.94 | Class: Surgical Scissors Sharp/Sharp
[     18.217     -94.362       254.4]
[15.631260155688263, 216.92316480600044, 146.23912106258123, -179.67999267578125, 0.30000001192092896, 45.959999084472656]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.454318, 141.1999969482422, 406.1000061035156, -176.50999450683594, -2.740000009536743, 46.779998779296875]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (430, 131) | Confidence: 0.93 | Class: Surgical Scissors Sharp/Sharp
[     96.216     -2.7259       271.6]
[153.65108399184405, 222.64827837122562, 134.55696575192644, -177.9499969482422, -1.4299999475479126, 45.95000076293945]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.91531535855866, 137.8000030517578, 400.6000061035156, -178.9199981689453, 0.5199999809265137, 46.59000015258789]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.72205414144135, 139.0, 403.20001220703125, -178.13999938964844, -1.3700000047683716, 45.2400016784668]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (309, 108) | Confidence: 0.94 | Class: Surgical Scissors Sharp/Sharp
[     50.846     -64.303       261.2]
[69.90603327495461, 221.4546767270287, 140.50198765846693, -179.44000244140625, -0.18000000715255737, 45.2599983215332]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.37630832072067, 134.4000015258789, 395.70001220703125, 178.0800018310547, 3.0199999809265137, 46.33000183105469]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.72205414144135, 139.3000030517578, 403.3999938964844, -178.02000427246094, -1.5, 45.33000183105469]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.83730567927932, 125.69999694824219, 384.8999938964844, 171.10000610351562, 8.90999984741211, 43.93000030517578]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[83.06780435855866, 136.3000030517578, 398.5, 179.07000732421875, 0.9300000071525574, 45.25]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (305, 146) | Confidence: 0.85 | Class: Surgical Scissors Sharp/Sharp
[     33.807     -51.656       272.6]
[68.15335358017249, 221.26711207947358, 138.6035904925136, -176.9600067138672, -3.049999952316284, 45.18000030517578]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (318, 165) | Confidence: 0.90 | Class: Surgical Scissors Sharp/Sharp
[     31.994     -38.081       277.2]
[68.6605663657532, 219.238898402712, 137.60223271511217, -175.13999938964844, -3.5199999809265137, 46.84000015258789]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.49155985855866, 135.3000030517578, 398.0, 179.8699951171875, 2.1700000762939453, 46.20000076293945]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (301, 130) | Confidence: 0.94 | Class: Surgical Scissors Sharp/Sharp
[     38.225     -58.622       264.3]
[64.78044509673083, 216.91853294831148, 141.7382876345331, -178.13999938964844, -1.25, 44.810001373291016]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[82.37630832072067, 136.9000015258789, 400.20001220703125, -179.2899932861328, 0.6600000262260437, 46.22999954223633]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (420, 97) | Confidence: 0.93 | Class: Surgical Scissors Sharp/Sharp
[     104.62     -21.501       264.9]
Error: Failed to retrieve coordinates.
Robot did not return coordinates
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (412, 134) | Confidence: 0.30 | Class: Surgical Scissors Sharp/Sharp
[     87.867     -9.2116       274.5]
[145.58527674235023, 224.63412481589438, 134.54777089627277, -177.38999938964844, -2.240000009536743, 45.040000915527344]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (274, 194) | Confidence: 0.96 | Class: Surgical Scissors Sharp/Sharp
[    -1.1303     -41.121       253.9]
[41.27742400228911, 154.92227282364524, 143.80067881910063, 179.5500030517578, 2.119999885559082, 46.290000915527344]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.454318, 141.5, 405.20001220703125, -177.07000732421875, -2.430000066757202, 47.13999938964844]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (308, 119) | Confidence: 0.51 | Class: Surgical Scissors Sharp/Sharp
[     46.688     -61.306         269]
[64.88684984669666, 230.96207055175807, 139.55461082922807, -177.52000427246094, -1.75, 45.939998626708984]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


No instrument found
[          0           0           0]
[81.80006382072068, 139.4000015258789, 404.0, -176.85000610351562, -1.0, 46.150001525878906]
Gripper command sent: 100 100
Response from robot: 
Gripper command sent: 0 100
Response from robot: 


C:\Users\maxis/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:906: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


Box center: (250, 96) | Confidence: 0.93 | Class: Surgical Scissors Sharp/Sharp
[     31.764     -98.594       271.2]
[27.05120133223923, 245.09646060900982, 138.0205787113361, -177.77000427246094, -1.8700000047683716, 45.04999923706055]
Gripper command sent: 100 100
Response from robot: 


KeyboardInterrupt: 